def product_schema(product) -> dict:
    
    return {"id": int(product[0]),
            "partNum": product[1],
            "familia": int(product[2]),
            "categoria": int(product[3]),
            "name": product[4],
            "description": product[5],
            "marks": int(product[6]),
            "sales_min_price": product[7],
            "sales_max_price": product[8],
            "precio": product[9],
            "currency_def": int(product[10]),
            "quantity": product[11],
            "tributari_classification": int(product[12]),
            "nombre_imagen": product[13],
            "descuento": product[14],
            "shipping": product[15],
            "condition": product[16],
            "category": product[17],
            "color": int(product[18]),
            "width": product[19],
            "height": product[20],
            "depth": product[21],
            "dimensions_unit": product[22],
            "weight": product[23],
            "weight_unit": product[24],
            "shipping_width": product[25],
            "shipping_height": product[26],
            "shipping_depth": product[27],
            "sku": product[28],
            "memoria_ram": product[29],
            "procesador": product[30],
            "disco_duro_gb": product[31],
            "disco_duro_tb": product[32],
            "disco_duro_ssd_gb": product[33],
            "disco_duro_ssd_tb": product[34]}

def products_schema(products) -> list:
    return {"ListaProductos": [product_schema(product) for product in products]}